version: "3"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./csv:/var/lib/postgresql/csv
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gis14
